version: "3"
services:
  app:
    image: suecharo/sapporo-web:1.0.1
    container_name: sapporo-web
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      - 3000:3000
    restart: always
    working_dir: /app
    command: ["yarn", "start"]
