version: "3"
services:
  app:
    image: suecharo/sapporo-web:v0.3.6
    container_name: sapporo-web-app
    restart: always
    volumes:
      - ${PWD}/etc/uwsgi:/opt/SAPPORO/SAPPORO-web/etc/uwsgi
      - ${PWD}/log/app:/opt/SAPPORO/SAPPORO-web/log/app
      - ${PWD}/src:/opt/SAPPORO/SAPPORO-web/src
    environment:
      - DEBUG=${SAPPORO_WEB_DEBUG:-False} # Django debug mode and Use SQLite
      - LANGUAGE_CODE=${SAPPORO_WEB_LANGUAGE_CODE:-en}
      - LOG_LEVEL=${SAPPORO_WEB_LOG_LEVEL:-INFO} # DEBUG or INFO
      - POSTGRES_DB=${SAPPORO_WEB_POSTGRES_DB:-sapporo-web}
      - POSTGRES_PASSWORD=${SAPPORO_WEB_POSTGRES_PASSWORD:-sapporo-web-passwd}
      - POSTGRES_PORT=${SAPPORO_WEB_POSTGRES_PORT:-5432}
      - POSTGRES_USER=${SAPPORO_WEB_POSTGRES_USER:-sapporo-web-user}
      - TIME_ZONE=${SAPPORO_WEB_TIME_ZONE:-Asia/Tokyo}
      - USER_SIGNUP=${SAPPORO_WEB_USER_SIGNUP:-True}
    user: ${UID:-0}:${GID:-0}
    command: ["/bin/bash", "entrypoint.uwsgi.sh"]
    networks:
      - sapporo
    depends_on:
      - database
  web:
    image: nginx:1.16.0-alpine
    container_name: sapporo-web-web
    restart: always
    volumes:
      - ${PWD}/etc/nginx/cache:/var/cache/nginx
      - ${PWD}/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/etc/nginx/run:/var/run/nginx
      - ${PWD}/etc/uwsgi:/etc/nginx/uwsgi
      - ${PWD}/log/nginx:/var/log/nginx
      - ${PWD}/src/static:/opt/SAPPORO/SAPPORO-web/src/static
    user: ${UID:-0}:${GID:-0}
    networks:
      - sapporo
    ports:
      - ${SAPPORO_WEB_PORT:-1121}:8080
    depends_on:
      - app
  database:
    image: postgres:11.4-alpine
    container_name: sapporo-web-database
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - sapporo
    environment:
      - POSTGRES_DB=${SAPPORO_WEB_POSTGRES_DB:-sapporo-web}
      - POSTGRES_PASSWORD=${SAPPORO_WEB_POSTGRES_PASSWORD:-sapporo-web-passwd}
      - POSTGRES_PORT=${SAPPORO_WEB_POSTGRES_PORT:-5432}
      - POSTGRES_USER=${SAPPORO_WEB_POSTGRES_USER:-sapporo-web-user}

volumes:
  postgres-data:

networks:
  sapporo:
    external:
      name: sapporo-network
