version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sapporo-web
    volumes:
      - ${PWD}:/app
      - /app/node_modules
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
    ports:
      - 3000:3000
    restart: always
    command: ["tail", "-f", "/dev/null"]
