version: "3"
services:
  app:
    image: suecharo/sapporo-web:v0.4.0
    container_name: sapporo-web-dev
    restart: always
    volumes:
      - ${PWD}/../src:/opt/SAPPORO/SAPPORO-web/src
      - ${PWD}/../log/app:/opt/SAPPORO/SAPPORO-web/log/app
    environment:
      - DEBUG=${SAPPORO_WEB_DEBUG:-True} # Django debug mode and Use SQLite
      - USER_SIGNUP=${SAPPORO_WEB_USER_SIGNUP:-True}
      - LANGUAGE_CODE=${SAPPORO_WEB_LANGUAGE_CODE:-en}
      - LOG_LEVEL=${SAPPORO_WEB_LOG_LEVEL:-DEBUG} # DEBUG or INFO
      - TIME_ZONE=${SAPPORO_WEB_TIME_ZONE:-Asia/Tokyo}
    user: ${UID:-0}:${GID:-0}
    command: ["entrypoint.sh"]
    networks:
      - sapporo
    ports:
      - ${SAPPORO_WEB_PORT:-1121}:8080

networks:
  sapporo:
    external:
      name: sapporo-network
